# Generated by Django 4.1.5 on 2023-02-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Esudiante",
            new_name="Estudiante",
        ),
    ]
