# Generated by Django 4.1.5 on 2023-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0002_rename_esudiante_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apelllido", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("profesion", models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name="estudiante",
            old_name="camada",
            new_name="comision",
        ),
    ]
