# Generated by Django 4.1.5 on 2023-02-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0003_profesor_rename_camada_estudiante_comision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profesor",
            old_name="apelllido",
            new_name="apellido",
        ),
    ]
