# Generated by Django 4.1.5 on 2023-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0004_rename_apelllido_profesor_apellido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("camada", models.IntegerField()),
                ("comision", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Entregable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("fecha", models.DateField()),
                ("entregado", models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="comision",
        ),
    ]
